title: Nikos Zarifis
logo: /assets/img/img1.jpeg
#logo: /assets/img/img2.jpg
description: Nikos Zarifis
show_downloads: true
markdown: kramdown
google_analytics:
theme: jekyll-theme-minimal

plugins:
    - jekyll/scholar

scholar:
  style: apa
  bibliography_template: bib
  source: ./_bibliography/
  bibliography: robust.bib
  replace_strings: true
  join_strings: true
  last_name: Zarifis

  query: "@*"
